[workspace]
members = [
    "ggml-sys",
    "ggml",
    "llama-rs",
    "llama-cli",
    "generate-ggml-bindings",
    "llama-webserver",
    "llama-wasm"
]
resolver = "2"

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
rand = "0.8.5"
