[package]
name = "llama-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llama-common = { path = "../llama-common" }


wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
